#!/bin/sh

if [ "$#" != "4" ]; then
  echo "usage: $(basename $0) OLD_NAME OLD_EMAIL NEW_NAME NEW_EMAIL"
  exit 1
fi

git filter-branch -f --env-filter "
OLD_NAME=\"$1\"
OLD_EMAIL=\"$2\"
NEW_NAME=\"$3\"
NEW_EMAIL=\"$4\"
if [ \"\$GIT_COMMITTER_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_COMMITTER_NAME=\"\$NEW_NAME\"
    export GIT_COMMITTER_EMAIL=\"\$NEW_EMAIL\"
fi
if [ \"\$GIT_AUTHOR_EMAIL\" = \"\$OLD_EMAIL\" ]
then
    export GIT_AUTHOR_NAME=\"\$NEW_NAME\"
    export GIT_AUTHOR_EMAIL=\"\$NEW_EMAIL\"
fi
" --tag-name-filter cat -- --branches --tags
