#!/bin/zsh
# This hook is run after every virtualenv is activated.


# If PROJECT_HOME is set and there is a directory with the same name
# as the currently activated virtualenv, then add that directory to
# the PYTHONPATH and cd into it, and if that project directory contains a
# 'bin' directory, add that to that PATH.
() {
    local project="${PROJECT_HOME}/$(basename ${VIRTUAL_ENV})"

    if [ -d "${project}" ]; then
        # record original PYTHONPATH only if it was set (even if empty)
        if [ -n "${PYTHONPATH+set}" ]; then
            export PREACTIVATE_PYTHONPATH="${PYTHONPATH}"
        fi
        export PREACTIVATE_PWD="$(pwd)"
        PYTHONPATH="${project}:${PYTHONPATH}"
        export PYTHONPATH="${project%:}"
        [ -d "${project}/bin" ] && export PATH="${project}/bin:${PATH}"
        cd "${project}"
    fi

    # The rehash may be needed if paths seem to be stale at times
    rehash
}
