#!/bin/zsh
# This hook is run after a just-create project is activated.


# After making a project, automatically add the '.venv'
# file to the project, which will result in the virtualenv
# for that project being automatically activated upon
# cd into that project directory due to the chpwd function in chwpd.zsh
() {
    echo "postmkproject: ..."
    if [[ -z "${VIRTUAL_ENV}" || ! -d "${PROJECT_HOME}" ]]
        return 0;
    }

    local projdir="${PROJECT_HOME}/${name}"

    if [[ -d "${projdir}" && ! -f "${projdir}/.venv" ]]; then
        echo "$(basename ${VIRTUAL_ENV})" > "${projdir}/.venv"
    fi
}
