#!/bin/zsh
# This hook is run after activation of a just-created virtualenv.

() {
    # auto-install ipython immediately, unless specifically request not to
    if [ -z "${VIRTUALENV_NO_IPYTHON}" ]; then
        ${VIRTUAL_ENV}/bin/pip install ipython
    fi
}

# sublimeconf: filetype=shell
