#!/bin/zsh
# This hook is run after a new project is activated.


# After making a project, automatically add the '.venv'
# file to the project, which will result in the virtualenv
# for that project being automatically activated when I
# cd into that project directory.
() {
    local name="$(basename ${VIRTUAL_ENV})"
    local project_dir="${PROJECT_HOME}/${name}"
    if [[ ! -f "${project_dir}/.venv" ]]
    then
        echo "${name}" > "${project_dir}/.venv"
    fi
}

# sublimeconf: filetype=shell
