#!/usr/bin/env zsh

# Display path to working tree root (source: prezto project)

local root="$(git rev-parse --show-toplevel 2> /dev/null)"

if [[ -n "$root" ]]; then
  print "$root"
  return 0
else
  print "$0: not a repository work tree: $PWD" >&2
  return 1
fi
