#!/usr/bin/env zsh

# Launch process disowned and detached from terminal, with stdout and stderr
# both being sent to a file in $TMPDIR/out with name of first param (program).

local outdir="${TMPDIR:-/tmp}/out"

command mkdir -p "${outdir}"

# the '&|' is zsh syntax for disowning the job
"$@" < /dev/null > ${outdir}/$(basename $1) 2>&1 &|
